### ISSUE TITLE
Show Projects on Explore Map

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#801] opened 2023-09-25 21:02 UTC
A user should be able to tap the "View in Explore" map from any project and see their project observations on the Explore screen.

<img width="192" alt="Screenshot 2023-09-25 at 2 01 36 PM" src="https://github.com/inaturalist/iNaturalistReactNative/assets/35536439/a592ef29-4418-4219-bff2-4815a9949a6a">

**Comment by jtklein** [comment] 2023-11-10 18:27
When navigating from Project screen to Explore screen, by pressing the View in Explore button:

1. Send the current project's id as navigation param to the Explore page.
2. Receive the id in the Explore screen and set the Explore filter of Project to this id. Requires https://github.com/inaturalist/iNaturalistReactNative/issues/886
3. Ensure that only observations from this project are retrieved, worldwide.

**Comment by jtklein** [comment] 2023-11-15 15:27
Duplicate of #893

**Closed by jtklein** 2023-11-15 15:27 UTC
Labels: enhancement
