### ISSUE TITLE
Multiple photos dots on Obs Detail not vertically centered

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#2119] opened 2024-09-19 19:03 UTC
**Describe the bug**
Currently on Obs Detail, when there are multiple photos in a single obs, the dots indicating multiple photos are not horizontally centered

**To Reproduce**
1. Go to obs detail for an obs with more than one photo

**Expected behavior**
The dots should all be horizontally centered (like on taxon detail)

**Screenshots**
![Screenshot 2024-09-19 at 11 15 46 AM 2](https://github.com/user-attachments/assets/0d0488c0-a3f2-4678-9fe5-ec862f9bab12)

**Comment by israr002** [comment] 2024-09-20 16:15
@kueda Pls assign this to me i am working on it

**Comment by israr002** [comment] 2024-09-23 17:36
@kueda the problem is in react-native-animated-dots-library and in the TaxonDetails we have added custom code to create carousel dots which is working fine
I propose to create a component and use it in both the screens (already tested) and remove react-native-animated-dots-library, also it is not maintained from last two years
whats your opinion ??


import classnames from "classnames";
import React from "react";
import { View } from "react-native";
import uuid from "react-native-uuid";

interface CarouselDotsProps {
  length: number;
  index: number;
}

const CarouselDots: React.FC<CarouselDotsProps> = ( { length, index } ) => {
  const dots = React.useMemo( () => Array.from(
    { length },
    () => uuid.v4( ) as string
  ), [length] );
  return (
    <View
      className="flex flex-row w-full justify-center items-center mb-3"
      pointerEvents="none"
    >
      {dots.map( ( dotKey, idx ) => (
        <View
          key={dotKey}
          className={classnames(
            "rounded-full bg-white m-[2.5]",
            idx === index
              ? "w-[4px] h-[4px]"
              : "w-[2px] h-[2px]"
          )}
        />
      ) )}
    </View>
  );
};

export default CarouselDots;

**Closed** 2024-09-24 20:15 UTC
Labels: bug
