### ISSUE TITLE
Tapping notification and going back immediately doesn't get marked as read

### ISSUE THREAD

**Issue by angielt** [inaturalist/iNaturalistReactNative#2261] opened 2024-10-16 21:38 UTC
**Describe the bug**
If you tap an unread notification and go back immediately from ObsDetails, the notification doesn't get marked as read. The request to mark the notification as read may never get to complete

**To Reproduce**
1. Go to Notifications
2. Tap on an unread notification
3. Immediately press back to go back to Notifications

**Expected behavior**
The notification should be marked as read when the notification is pressed. Check with Abhas

**Screenshots**

**Context (please complete the following information):**
 - Device: [Android]
 - OS: [e.g. Android 14]
 - App version: [e.g. 0.50.0]

**Comment by kueda** [comment] 2024-10-16 23:58
Duplicate of #1613

**Closed by kueda** 2024-10-16 23:58 UTC
Labels: bug
