### ISSUE TITLE
Taxon Detail view when accessed through suggestions

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1565] opened 2024-05-20 19:59 UTC
When a user lands on taxon detail from suggestions, they have a high likelihood of exiting the obs create flow through too many external buttons.

When a user lands on taxon detail while coming from the suggestions screen, hide the following UI elements:
- [ ] the green explore button
- [ ] the kebab menu at the top
- [ ] the entire tab bar

**Comment by kueda** [comment] 2024-06-10 21:39
Duplicate of #1549

**Closed by kueda** 2024-06-10 21:39 UTC
Labels: enhancement, ux

**Comment by loarie** [comment] 2024-06-10 21:44
can this be closed?
