### ISSUE TITLE
When there is only 1 ID suggestion, hide the nearby/all suggestions section and remove the "No ID" text and button

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1490] opened 2024-05-01 23:44 UTC
**Describe the bug**
When the online model has only one suggestion for a photo, it displays a top ID suggestion and the "iNaturalist has no ID suggestions" text (assumably because there are no nearby suggestions in addition to the top suggestion)
![IMG_C7CF8E5655BA-1](https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/651919d3-4b86-474a-97aa-016c257a5032)

**To Reproduce**
1. Make sure debug mode is on
2. Go to https://www.inaturalist.org/observations/208846726 on desktop
3. Take a picture of the screen with the AI camera
4. View suggestions

**Expected behavior**
When only one ID comes up for the AI camera, show only the Top ID suggestion with that suggestion, hide the nearby/all suggestions suggestions section, and make sure no error pops up. 

**Context (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 17.4.1
 - App version: 0.32.0 (88)

**Comment by albullington** [comment] 2024-05-02 00:01
Closing because this is a duplicate of https://github.com/inaturalist/iNaturalistReactNative/issues/1474

**Comment by abhasinat** [comment] 2024-05-21 19:23
Reopening because this was not fixed by #1474 and was reported again in the testing doc.

**Closed** 2024-06-05 19:11 UTC
Labels: bug
