### ISSUE TITLE
Tapping improve permissions with location button should reload results with location

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1807] opened 2024-07-15 21:51 UTC
**Describe the bug**
On the Suggestions screen, tapping Improve Suggestions Using Location button shows the permissions prompt, but it doesn't reload online suggestions with location permissions.

**To Reproduce**
1. Go to Suggestions
2. Tap on Improve Suggestions Using Location button
3. See "Use Location" button is still on screen while Improve Suggestions is also shown (this first button should be hidden)
4. Give permission to use location
5. See online suggestion results without location 

**Expected behavior**
The Changes to Suggestions [issue](https://github.com/inaturalist/iNaturalistReactNative/issues/1592) shows what the UI should look like for the various suggestions screen location states. There should only be one location button at a time.

Functionality-wise, a user should see online suggestion results with the correct location as soon as they give location permissions.

We have a few other related issues for location not working well in suggestions (https://github.com/inaturalist/iNaturalistReactNative/issues/1772) and adding the improve with location button (https://github.com/inaturalist/iNaturalistReactNative/issues/1755). Would be good for one person to tackle all of these.

**Context (please complete the following information):**
 - OS: iOS
- App version: v0.36.0+101

**Comment by jtklein** [comment] 2024-07-16 14:46
Is this a duplicate of #1755 checklist item 3?

**Comment by albullington** [comment] 2024-07-16 14:55
yeah, looks like it's covered by that issue. will close

**Closed** 2024-07-16 14:55 UTC
Labels: bug
