### ISSUE TITLE
Tapping on notification for a certain observation consistently causes app to crash

### ISSUE THREAD

**Issue by tiwane** [inaturalist/iNaturalistReactNative#1424] opened 2024-04-19 18:55 UTC
**Describe the bug**
Tapping on a notification for https://www.inaturalist.org/observations/142433927 consistently causes app to crash.

**To Reproduce**
1. Be Tony and open notifications
2. Tap on a notification for https://www.inaturalist.org/observations/142433927
3. App crashes

**Expected behavior**
The app should not crash.

**Screenshots**

![image](https://github.com/inaturalist/iNaturalistReactNative/assets/15896181/21a2a615-6fb1-4fc8-8480-f20b65705b94)

**Context (please complete the following information):**
- Device: iPhone 13 Pro
 - OS: iOS 17.4.1
 - App version: 0.31.1+86

**Additional context**

**Comment by jtklein** [comment] 2024-04-23 15:28
This might be a possible duplicate of https://github.com/inaturalist/iNaturalistReactNative/issues/1404 as it shows the same error message.

**Comment by jtklein** [comment] 2024-04-25 12:05
Closed by https://github.com/inaturalist/iNaturalistReactNative/commit/87c753501a72c4be8b78494da731ea1aa7ea4856

**Closed by jtklein** 2024-04-25 12:05 UTC
Labels: bug
