### ISSUE TITLE
Review button should lead to a modal that asks a user to leave a review

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1450] opened 2024-04-23 16:11 UTC
Right now, the review button on the donate screen is clickable but does nothing. It should open a native modal that allows a user to add stars and leave a review in the App Store. iOS has native components for this.

<img width="420" alt="13" src="https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/a474011b-5867-48d3-b2f5-c65f1560d66e">

**Comment by jtklein** [comment] 2024-04-23 16:13
Duplicate of #1370

**Closed by jtklein** 2024-04-23 16:13 UTC
Labels: bug
