### ISSUE TITLE
App crash when using Expore to identify

### ISSUE THREAD

**Issue by tiwane** [inaturalist/iNaturalistReactNative#1415] opened 2024-04-18 04:38 UTC
**Describe the bug**
I was using the Explore screen to add some IDs when the app crashed after tapping on an obs. I can't remember exact sequence of events, but I'll provide as much detail as I can remember.

**To Reproduce**
1. Go to Explore
2. Select Observations
3. Choose nearby observations, and filter for unreviewed observations that need ID.
4. Scroll through obs and add IDs to a few. I think I added IDs (and some DQA votes and comments) to about 5-6 of them.
5. Tap on next obs and the app crashes.

**Expected behavior**
The app should not crash.

**Screenshots**
![50FB1709-33BC-4F0A-95B0-27BED7BC741B_1_102_o](https://github.com/inaturalist/iNaturalistReactNative/assets/15896181/ba703679-6c70-478a-9702-5c240b1389d4)

**Context (please complete the following information):**
- Device: iPhone 13 Pro
 - OS: iOS 17.4.1
 - App version: 0.30.0+84

**Additional context**

**Comment by jtklein** [comment] 2024-04-23 15:22
This might be a possible duplicate of #1404 as it shows the same error message.

**Comment by jtklein** [comment] 2024-04-25 12:05
Closed by https://github.com/inaturalist/iNaturalistReactNative/commit/87c753501a72c4be8b78494da731ea1aa7ea4856

**Closed by jtklein** 2024-04-25 12:05 UTC
Labels: bug
