### ISSUE TITLE
UploadIcon component

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#433] opened 2023-02-03 18:28 UTC
<img width="91" alt="Screen Shot 2023-02-03 at 10 25 14 AM" src="https://user-images.githubusercontent.com/35536439/216679080-1d899cd1-2574-4bcd-8266-5d217913eb77.png">

When an observation has not been uploaded to the server, we'll need an UploadIcon component in one of three states:
- [ ] Up arrow encircled by dots - upload has not started
- [ ] Up arrow with circular progress bar that fills in as the upload progresses
- [ ] Checkmark for completed upload

The default color for the arrow should be:
- [ ] #454545 (darkGray)

The default color for the checkmark should be:
- [ ] #74AC00 (inatGreen)

The icon will need to accept at least two props: color and uploadStatus.

**Comment by angielt** [comment] 2023-02-06 05:20
may be duplicate of https://github.com/inaturalist/iNaturalistReactNative/issues/400#issue-1559023468 ?

**Comment by kueda** [comment] 2023-02-09 00:31
Yup, looks like a duplicate.

**Closed by kueda** 2023-02-09 00:31 UTC
Labels: enhancement
