### ISSUE TITLE
Radio bottom sheet UI fixes

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1812] opened 2024-07-15 22:48 UTC
Right now, the radio bottom sheets seem to be having some UI issues - the font is not Lato and the style is incorrect. Please make sure the styling matches the [designs](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=7082-35843&t=xXLHdwIEYusfw5TS-11).

![Screenshot 2024-07-15 at 3 44 41 PM](https://github.com/user-attachments/assets/f956e73a-8136-4207-9fa6-af16b5d6e64f)

**Comment by albullington** [comment] 2024-07-15 23:47
Closing because this is a duplicate of https://github.com/inaturalist/iNaturalistReactNative/issues/1798

**Closed by albullington** 2024-07-15 23:47 UTC
Labels: bug, UI
